\ProvidesClass{homework}

\LoadClass[a4paper,12pt]{article}

\usepackage[top=2cm]{geometry}
\usepackage{microtype}

% xelatex
%needed by polyglossia
\usepackage{fontspec}
% warn about bad practices
\usepackage[l2tabu]{nag}
% replacement for babel
\usepackage{polyglossia}

\setmainlanguage{finnish}

% pdflatex
%\usepackage[finnish]{babel}
%\usepackage[T1]{fontenc}
%\usepackage[utf8]{inputenc}

% vim: ft=tex
