#!/bin/bash

alias lsc='ls --color=auto'
alias l='lsc'
alias la='lsc -a'
alias ll='lsc -l'
alias lla='lsc -la'
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias udm='udisksctl mount --block-device'
alias udu='udisksctl unmount --block-device'
alias news='newsbeuter -r'
