#!/bin/bash

c_off='\[\e[0m\]'
c_bla='\[\e[0;30m\]' c_red='\[\e[0;31m\]' c_gre='\[\e[0;32m\]' c_yel='\[\e[0;33m\]'
c_blu='\[\e[0;34m\]' c_pur='\[\e[0;35m\]' c_cya='\[\e[0;36m\]' c_whi='\[\e[0;37m\]'

# git repo status
git_prompt="/usr/share/git/git-prompt.sh"
if [[ -r "$git_prompt" ]]; then
    . "$git_prompt"

    GIT_PS1_SHOWDIRTYSTATE='y'
    GIT_PS1_SHOWSTASHSTATE='y'
    GIT_PS1_SHOWUNTRACKEDFILES='y'
    GIT_PS1_SHOWCOLORHINTS='y'

    _ps1_repo_status() {
        __git_ps1 " (%s)"
    }
else
    _ps1_repo_status() {
        :
    }
fi

# user color
((UID == 0)) && c_u="$c_red" || c_u="$c_blu"

# host color
[[ -n "$SSH_CLIENT" ]] && c_h="$c_red" || c_h="$c_blu"

PS1="${c_u}\u${c_off}@${c_h}\h${c_off}:${c_gre}\W${c_off}${c_cya}\$(_ps1_repo_status)${c_off}\$ "

unset c_{off,bla,red,gre,yel,blu,pur,cya,whi,u,h} git_prompt
